Garyshker/Main/Main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from Dobro.admin import dobro_admin_site
from Obrazovanie.admin import report_admin_site, video_admin_site
from Garyshker.admin import super_admin_site




urlpatterns = [
    path('admin/', super_admin_site.urls),
    path('dobro_admin', dobro_admin_site.urls),
    path('report_admin', report_admin_site.urls),
    path('video_admin', video_admin_site.urls),
    path('', include('Garyshker.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Garyshker/Main/Obrazovanie/models.py
from django.db import models
from django.utils.text import slugify
from time import time
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()




def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + '-' + str(int(time()))







class Type(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, unique=True)
    # item = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.name)


    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.name)
        super().save(*args, **kwargs)



class Genre(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, unique=True)


    def __str__(self):
        return str(self.name)


    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.name)
        super().save(*args, **kwargs)



class Format(models.Model):
    name = models.CharField(max_length=120)


    def __str__(self):
        return str(self.name)




class Item(models.Model):
    type = models.ForeignKey(Type, on_delete=models.CASCADE, blank=True, null=True)
    format = models.ForeignKey(Format, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=120)
    # slug = models.SlugField(blank=True, unique=True)
    number_of_item = models.IntegerField()
    guest = models.CharField(max_length=120, default='Secret')
    image = models.ImageField(blank=True, upload_to='item-image')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, blank=True, null=True)
    podcast = models.FileField(upload_to='item-podcast', default='Please upload video')
    description_video = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    leading = models.CharField(max_length=120, blank=True)
    views = models.PositiveIntegerField(default=0)
    clip = models.CharField(blank=True, max_length=120)




    def __str__(self):
        return str(self.name)




class Report(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    # slug = models.SlugField(blank=True)
    title = models.CharField(max_length=120)
    image = models.ImageField(blank=True, upload_to='report-image')
    header = models.TextField(blank=True, null=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    # status = models.CharField(max_length=120, choices=STATUS_CHOICES, default='Checking')
    wrote_date = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    moderation = models.BooleanField("Проверено", default=False)
    # restrict_comment = models.BooleanField('Ограничить комментарий', default=False)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)


    def __str__(self):
        return str(self.title)





class Comment(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    reply = models.ForeignKey('Comment', null=True, related_name='replies', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '{}-{}'.format(self.report.title, str(self.user.username))

Garyshker/Main/Obrazovanie/forms.py
from .models import *
from django import forms





class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Написать', 'rows': 1, 'cols': 3}))
    class Meta:
        model = Comment
        fields = ('content',)




class ReportCreateForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = (
            'genre',
            'title',
            'header',
            'body',
            'image'
        )

        widgets = {
            'body':forms.Textarea(attrs={'cols': 46, 'rows': 3}),
            'image': forms.FileInput()

        }
        # field_order = ['genre', 'title', 'body', 'header']

#
# class CommentEditForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = {
#             'content'
#         }

Garyshker/Main/Obrazovanie/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import *
from django.urls import reverse
from .forms import *
from django.views.generic import View
from django.db.models import F
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.db.models import Count





class SearchField(View):
    model = Item
    template = 'obrazovanie/search.html'
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            search = request.POST['search']
        else:
            search = ''
        item = self.model.objects.filter(name__icontains=search)
        context = {
            'item': item
        }
        return render(request, self.template, context)


class SearchFieldReport(View):
    model = Report
    template = 'obrazovanie/search_report.html'
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            search_report = request.POST['search_report']
        else:
            search_report = ''
        report = self.model.objects.filter(title__icontains=search_report)
        context = {
            'report': report
        }
        return render(request, self.template, context)



def show_item(request):
    type = Type.objects.all()
    item = Item.objects.all()
    genre = Genre.objects.all()


    context = {
        'type': type,
        'item': item,
        'genre': genre
    }
    return render(request, 'obrazovanie/obrazovanie.html', context)


def genre_detail(request, slug):
    genre_all = Genre.objects.all()
    genre = Genre.objects.filter(slug=slug)
    return render(request, 'obrazovanie/genre_detail.html', context={'genre':genre, 'genre_all': genre_all})


def item_detail(request, id):
    item = Item.objects.get(id=id)
    item.views = item.views + 1
    item.save()
    return render(request, 'obrazovanie/item_detail.html', context={'item': item})



def all_reports(request):
    reports = Report.objects.filter(moderation=True)
    # reports = Report.objects.all()
    genre_all = Genre.objects.all()

    # genre = Genre.objects.filter(slug=slug)
    # if reports.likes.get(id=request.user.id).exists():
    #
    #     is_liked=True


    context = {
        'reports': reports,
        'genre_all': genre_all,

        # 'genre':genre
    }
    return render(request, 'obrazovanie/all_reports.html', context)






def report_detail(request, id):
    report = Report.objects.get(id=id)
    comments = Comment.objects.filter(report=report, reply=None).order_by('-id')
    genre_all = Genre.objects.all()
    popular_post = Report.objects.annotate(like_report=Count('likes')).order_by('-like_report')[:4]
    # popular_post_comment = Comment.objects.filter(report = popular_post[0], reply=None)
    is_liked = False
    if report.likes.filter(id=request.user.id).exists():
        is_liked=True


    is_favourite=False
    if report.favourite.filter(id=request.user.id).exists():
        is_favourite=True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs=None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(report=report, user = request.user, content=content, reply=comment_qs)
            comment.save()
            return HttpResponseRedirect(reverse('report_detail_url', kwargs={'id': report.id}))

    else:
        comment_form = CommentForm()


    context = {
        'report': report,
        'is_favourite': is_favourite,
        'comments': comments,
        'comment_form': comment_form,
        'is_liked': is_liked,
        'genre_all': genre_all,
        'popular_post': popular_post,
        # 'popular_post_comment': popular_post_comment



    }

    if request.is_ajax():
        html = render_to_string('obrazovanie/comments.html', context, request=request)
        return JsonResponse({'form':html})

    return render(request, 'obrazovanie/report_detail.html', context)


def genre_detail_report(request, slug):
    genre_all = Genre.objects.all()
    genre = Genre.objects.filter(slug=slug)

    return render(request, 'obrazovanie/genre_detail_report.html', context={'genre': genre, 'genre_all':genre_all})




def like_report(request):
    # report = Report.objects.get(id=request.POST.get('report_id'))
    report = Report.objects.get(id=request.POST.get('id'))
    is_liked = False
    if report.likes.filter(id=request.user.id).exists():
        report.likes.remove(request.user)
        is_liked=False
    else:
        report.likes.add(request.user)
        is_liked=True

    context = {
        'report': report,
        'is_liked': is_liked

    }
    if request.is_ajax():
        html = render_to_string('obrazovanie/like_section.html', context, request=request)
        return JsonResponse({'form':html})
    # return HttpResponseRedirect(reverse('report_detail_url', kwargs={'id':report.id}))


def report_create(request):
    if request.method == 'POST':
        form = ReportCreateForm(request.POST, request.FILES)
        if form.is_valid():
            report = form.save()
            report.author = request.user
            report.save()
            # if report.status == 'READY':
            #
            #
            return HttpResponseRedirect(reverse('after_writing_post_url'))
    else:
        form = ReportCreateForm()
    return render(request, 'obrazovanie/report_create.html', context={'form':form})



def after_writing_post(request):
    return render(request, 'obrazovanie/after_writing_post.html')



def comment_delete(request, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

Garyshker/Main/Obrazovanie/templates/obrazovanie/after_writing_post.html
{% extends 'base.html' %}


{% block title %}

  Образование

{% endblock %}


{% block content %}

<h2 id="dobro_tech" class="feedback_report">Спасибо ваш пост проверяется</h2>

{% endblock %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/all_reports.html
{% extends 'base.html' %}


{% block title %}

Образование


{% endblock %}


{% block subtitle %}

<div class="item-genre">
  <div class="item-type">
      <li class="item_sq">
        <a style="text-decoration:none" href="{% url 'obrazovanie_url' %}">Смотреть </a>
      </li>
      <li class="active" id="items_sq2">
        <a style="text-decoration:none" class="nav_genre" id="active_nav" href="{% url 'all_reports_url' %}">Читать</a>
      </li>

  </div>
    <div class="item-genres">

      {% for genre in genre_all %}
        <a style="text-decoration:none" class="item_ds" href="{% url 'genre_detail_reports_url' slug=genre.slug %}">{{ genre.name }}</a>
        {% endfor %}
    </div>


</div>


  <!-- {% for genre in genre_all %}
    <a href="{% url 'genre_detail_reports_url' slug=genre.slug %}">{{ genre.name }}</a>
  {% endfor %}


    <div class="two_but">
      <a class="di" href="{% url 'obrazovanie_url' %}">Смотреть</a>


      <a href="{% url 'all_reports_url' %}">Читать</a>
    </div> -->

{% endblock %}


{% block content %}

<!-- Мен, Нурсат уакытша комменттеп койдым поиск болмайтын болды -->

<!-- <div class="res-search">
  {% csrf_token %}
  <input id="search_report" type="searh" class="search-food" name="search-food" placeholder="Поиск">
</div>


<div class="header-res">
  <nav>
    <ul id="search_results">

    </ul>
  </nav>
</div> -->


<!-- контейнер ашайын деп едим -->

<div class="container-report">



    <div class="report">
      {% for report in reports %}

         <div class="report-detail">
           <a style="text-decoration:none" class="item_ds" href="{% url 'report_detail_url' id=report.id %}">
           <div class="report-image" style="background:url('{{report.image.url}}')">

           </div>
            <div class="report-title">
                {{ report.title }}
            </div>
            </a>
            <div class="report-author">
              <a class="item_ds" href="{% url 'someone_profile_url' id=report.author.id %}">by: @{{ report.author }}</a>
            </div>
         </div>

         {% endfor %}


    </div>





</div>
{% endblock %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/comments.html
<div class="container-fluid mt-2">
  <div class="form-group row">
    <form method="post" class="com-form">
      {% csrf_token %}
        <div class="com-form">
          <div class="com-form-text">
            {{ comment_form.as_p }}
          </div>
          <div class="com-form-input">
            {% if request.user.is_authenticated %}
              <input type="submit" value="Отправить" class="btn btn-default">
            {% else %}
              <input type="submit" value="Отправить" class="btn btn-default" disabled>
            {% endif %}
          </div>

        </div>
    </form>
  </div>
</div>

<a style="text-decoration:none" id="item_ds2" href="#" type="submit" class="comment-btn">

  {{ comments.count }} <i class="fa fa-comment"></i>Комментарий
  <!-- {{ comments|pluralize }} -->
</a>



{% for comment in comments %}

<div class="comment_form" id="comment_form">
  <blockquote class="blockquote">
    <p class="mb-0" id="report_ty"><small>{{ comment.content }}</small></p>
    <footer class="blockquote-footer"><small>by {{ comment.user|capfirst }}| {{ comment.timestamp|timesince }} ago</small>
      <a style="text-decoration:none" class="comment-reply-btn" href=""><button type="button" name="button" id="reply_btn" class="reply-btn btn btn-outline-dark btn-sm">Ответить</button></a>
      {% if user == comment.user %}
      <a style="text-decoration:none" id="com_del_btn" class="btn btn-outline-dark btn-sm" href="{% url 'comment_delete_url' id=comment.id %}">Удалить</a>
      {% endif %}
    </footer>

    <div id="comment-reply" class="container mt-4" style="display:none;">
      {% for reply in comment.replies.all %}
      <blockquote class="blockquote">
        <p class="mb-0" id="report_ty"><small>{{ reply.content }}</small></p>
        <footer class="blockquote-footer"><small>| by {{ reply.user|capfirst }} | {{ reply.timestamp|timesince }} ago</small></footer>
      </blockquote>
      {% endfor %}
      <div class="comment-reply">
        <form method="post" class="reply-form">
          {% csrf_token %}
            <input type="hidden" name="comment_id" value="{{ comment.id }}">
            <div class="com_re">
              {{ comment_form.as_p }}

            </div>
          {% if request.user.is_authenticated %}

            <input id="reply_send" type="submit" value="Отправить" class="btn btn-default">
          {% else %}
            <input id="reply_send" type="submit" value="Отправить" class="btn btn-default" disabled>
          {% endif %}
        </form>
      </div>
    </div>

  </blockquote>
</div>

{% endfor %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/genre_detail.html
{% extends 'base.html' %}


{% block title %}

Образование


{% endblock %}


{% block subtitle %}

<!-- {% for genre in genre_all %}

  <a href="{% url 'genre_detail_url' slug=genre.slug %}">{{ genre.name }}</a>

{% endfor %}

  <div class="">
    <a href="{% url 'obrazovanie_url' %}">Смотреть</a>

    <a href="{% url 'obrazovanie_url' %}">Читать</a>
  </div> -->


  <div class="item-genre">
    <div class="item-type">
        <li class="active">
          <a style="text-decoration:none" id="item_ds" href="{% url 'obrazovanie_url' %}">Смотреть </a>
        </li>
        <li>
          <a style="text-decoration:none" class="nav_genre" id="active_nav" id="item_ds" href="{% url 'all_reports_url' %}">Читать</a>
        </li>

    </div>
    <div class="item-genres">

      {% for genre in genre_all %}
      <li>
        <a style="text-decoration:none" id="item_ds" href="{% url 'genre_detail_url' slug=genre.slug %}">{{ genre.name }}</a>
      </li>
        {% endfor %}
    </div>
  </div>


{% endblock %}


{% block content %}

 {% for genre in genre %}
 <div class="item-obr" style="margin-top:102px;">

    {% for item in genre.item_set.all %}

    <div class="item">
      <a href="{% url 'item_detail_url' id=item.id %}" id="item_ds">
        <div class="item-detail" style="background:url('{{item.image.url}}')">
          <div class="item-name">
            <div class="item-topic">
              {{ item.name }}
            </div>
            <div class="item-body">
                #{{ item.number_of_item }}|
                Тема: {{ item.genre }}
                {{ item.guest }}
            </div>
          </div>
        </div>
      </a>
    </div>

    {% endfor %}
</div>
  {% endfor %}




{% endblock %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/genre_detail_report.html
{% extends 'base.html' %}


{% block title %}

Образование


{% endblock %}


{% block subtitle %}


<div class="item-genre">
  <div class="item-type">
    {% with url_name=request.resolver_match.url_name %}
      <a style="text-decoration:none" class="active" id="item_ds" href="{% url 'obrazovanie_url' %}">Смотреть </a>
      <li class="active">
        <a style="text-decoration:none" class="{% if url_name == 'all_reports_url' %}active{% endif %}" id="item_ds" href="{% url 'all_reports_url' %}">Читать</a>

      </li>
    {% endwith %}
  </div>
  <div class="item-genres">

    {% for genre in genre_all %}
      <li >
        <a style="text-decoration:none" class="menu" sid="item_ds" href="{% url 'genre_detail_reports_url' slug=genre.slug %}">{{ genre.name }}</a>
      </li>

      {% endfor %}

  </div>

</div>

{% endblock %}


{% block content %}

  {% for genre in genre %}

  <div class="container-report">


  <div class="report">

    {% for report in genre.report_set.all %}




    <div class="report-detail">
      <a id="item_ds" href="{% url 'report_detail_url' id=report.id %}">
      <div class="report-image" style="background:url('{{report.image.url}}')">

      </div>
       <div class="report-title">
           {{ report.title }}
       </div>
       </a>
       <div class="report-author">
         <a id="item_ds" color:;" href="{% url 'someone_profile_url' id=report.author.id %}">by: @{{ report.author }}</a>
       </div>
    </div>



    {% endfor %}

  </div>
  </div>


  {% endfor %}

{% endblock %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/item_detail.html
{% extends 'base.html' %}

{% block title %}

Образование


{% endblock %}


{% block subtitle %}


{% endblock %}


{% block content %}


<div class="bg_img_1"></div>
<div class="form_wrapper_1">
  <div class="form_container">
    <div class="title_container">
      <h2>{{ item.name }}</h2>
      <!-- <h3>Created with pure CSS Only!</h3> -->
    </div>
    <div>
      <!-- {% csrf_token %} -->
      <div class="row clearfix">
        <div class="col_half">
          <label>Ведущий</label>
          <div class="input_field">
            {{ item.leading }}
            <!-- <input type="text" name="first_name" placeholder="" required /> -->
          </div>
        </div>
        <div class="col_half">
          <label>Гость</label>
          <div class="input_field" id="create_post_genre">
            <!-- <input type="text" name="last_name" placeholder="" /> -->
            {{ item.guest }}
          </div>
        </div>
      </div>
      <div class="row clearfix">
        <div class="textarea_field" id = write-post>
          {{ item.description_video }}

        </div>
        <!-- <div class="col_half">
          <label>Phone</label>
          <div class="input_field">
            <input type="tel" name="phone" placeholder="Phone no" pattern="[0-9]{10}" />
          </div>
        </div> -->
      </div>
      <div class="row clearfix">
        <div style="margin:0 auto;">
          <label></label>
          <div class="textarea_field">
            <!-- <textarea cols="46" rows="3" name="comments"></textarea> -->
            {% if item.podcast.url %}
              <audio controls controlsList="nodownload" id="audio_podcast">
                <source src="{{ item.podcast.url }}"/>
              </audio>
              <!-- <iframe src="{{item.podcast.url}}" width="" height=""></iframe> -->
            {% else %}
              <p>There is no podcast</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



    <!-- <h3></h3>

    <div class="">
      Ведущий:
    </div>

    <div class="">
      Гости: {{ item.guest }}
    </div>
    <div class="">
      <img src="{{item.image.url}}" alt="">
    </div> -->

    <!-- <video width="400" controls>
      <source src="{{item.video.url}}" type="video/mp4">
    </video> -->



    <!-- <div class="">
      {{ item.views }} views
    </div> -->

    <!-- <div class="">
    </div> -->






{% endblock %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/like_section.html
{% if request.user.is_authenticated %}
<form action="{% url 'likes_url' %}" method="post" class="like_main">
  {% csrf_token %}
    <div class="like-section">

      <div class="like-body" id="like_count">
        <p class="like-count">{{ report.likes.count }}</p>

        {% if is_liked %}
          <button type="submit" id="like" name="report_id" value="{{report.id}}" class="btn-like"><i id="like-rep" class="fa fa-heart">Нравится</i></button>
        {% else %}
          <button type="submit" id='like' name="report_id" value="{{report.id}}" class="btn-like2"><i id="like-rep2" class="fa fa-heart">Нравится</i></button>
        {% endif %}
      </div>
    </div>
</form>
{% else %}
<a id="like-href" href="/login">
  <button type="" class="btn btn-danger" name="post_id" value="{{report.id}}">Like</button>
    {{ report.likes.count }}
</a>

{% endif %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/obrazovanie.html
{% extends 'base.html' %}


{% block title %}

Образование


{% endblock %}

{% block subtitle %}
  <div class="item-genre">
      <div class="item-type">
          <li class="active">
            <a style="text-decoration:none" href="{% url 'obrazovanie_url' %}">Смотреть </a>
          </li>
          <li>
            <a class="nav_genre" id="active_nav" style="text-decoration: none;" href="{% url 'all_reports_url' %}">Читать</a>
          </li>

      </div>
      <div class="item-genres">

        {% for genre in genre %}
        <li>
          <a style="text-decoration:none" href="{% url 'genre_detail_url' slug=genre.slug %}">{{ genre.name }}</a>
        </li>
          {% endfor %}
      </div>


  </div>
{% endblock %}



{% block content %}

    <!-- <div class="res-search">
      {% csrf_token %}
      <input id="search" type="searh" class="search-food" name="search-food" placeholder="Поиск">
    </div>


    <div class="header-res">
      <nav>
        <ul id="search_results">

        </ul>
      </nav>
    </div> -->


<div class="container-obr">
 {% for type in type %}
  <h3 class="type-name-obr">{{ type.name }}</h3>
    <div class="item-obr">
      {% for item in type.item_set.all %}
        <div class="item">
          <a href="{% url 'item_detail_url' id=item.id %}" style="text-decoration:none" class="item_ds">
            <div class="item-detail" style="background:url('{{item.image.url}}')">
              <div class="item-name">
                <div class="item-topic">
                  {{ item.name }}
                </div>
                <div class="item-body">
                    #{{ item.number_of_item }}|
                    Тема: {{ item.genre }}
                    {{ item.guest }}
                </div>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  {% endfor %}
</div>



{% endblock %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/report_detail.html
{% extends 'base.html' %}


{% block title %}

Образование


{% endblock %}


{% block subtitle %}


  <div class="item-genre">
    <div class="item-type">
      {% with url_name=request.resolver_match.url_name %}
        <a class="active" style="text-decoration:none" id="item_ds" href="{% url 'obrazovanie_url' %}">Смотреть </a>
        <a class="{% if url_name == 'all_reports_url' %}active{% endif %}" id="item_ds" href="{% url 'all_reports_url' %}">Читать</a>
      {% endwith %}
    </div>
    <div class="item-genres">

      {% for genre in genre_all %}
        <a style="text-decoration:none" class="item_ds" href="{% url 'genre_detail_reports_url' slug=genre.slug %}">{{ genre.name }}</a>
        {% endfor %}
    </div>

  </div>



{% endblock %}


{% block content %}

  <div class="container-rep-detail">

      <div class="rep-detail content">

        <div class="rep-author-date">
          <div class="rep-author-img">
            <img src="{{report.author.profile.images.url}}" alt="">
          </div>
          <div class="rep-author">
            <a style="text-decoration:none" class="item_ds" href="{% url 'someone_profile_url' id=report.author.id %}">
              @{{ report.author }}
            </a>
          </div>
            <div class="rep-date">
              {{ report.wrote_date|timesince }} ago
            </div>
        </div>

        <div class="rep-title">
          <h5>{{ report.title }}</h5>
        </div>



        <div class="rep-body">
          <textarea id="com-area" class="rep-textarea" name="name" rows="19" cols="90">{{ report.body }}</textarea>

          <div id="like-section">
          {% include 'obrazovanie/like_section.html' %}
          </div>
          <div class="main-comment-section">
          {% include 'obrazovanie/comments.html' %}
          </div>
        </div>
      </div>

      <div class="rep-rec content">
        <h5 class="reccomend_table">Рекомендуем</h5>
        {% for popular_post in popular_post %}
          <div class="reccomend" >
            <div class="rec">
              <a style="text-decoration:none" href="{% url 'report_detail_url' id=popular_post.id %}" class="item_ds">
                {{ popular_post }}
              </a>
            </div>
              <i id="like-rep" class="fa fa-heart">
                {{ popular_post.likes.count }}
              </i>
              <i id="like-rep" class="fa fa-comment">
                {{popular_post.comment_set.count}}

              </i>
              <!-- {% for comment in popular_post.comment_set.all %}
              <div class="" style="color:white;">
                {{comment.user.count}}

              </div>
              {% endfor %} -->

          </div>


        {% endfor %}
      </div>




  </div>



{% endblock %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/search.html
{% if item.count > 0 %}

  {% for item in item %}
  <div>
    <li>
      <a href="{% url 'item_detail_url' id=item.id %}">{{ item.name }}</a>

      <div>
        {{ item.number_of_item }}
      </div>

      <div class="">
        {{ item.guest }}
      </div>

      <div class="">
        {{ item.genre }}
      </div>

      <div class="">
        <a href="{% url 'item_detail_url' id=item.id %}">
          <img style="width: 190px; height: 150px;" src="{{ item.image.url }}" alt="">
        </a>
      </div>
      </li>
    </div>
  {% endfor %}

  {% endif %}

Garyshker/Main/Obrazovanie/templates/obrazovanie/search_report.html
{% if report.count > 0 %}


{% for report in report %}

  <a style="text-decoration:none; color:inherit;" href="{% url 'report_detail_url' id=report.id %}">
    <div class="">
      <h5>{{ report.title }}</h5>
      {{ report.author }}
      <div class="">
        {{ report.wrote_date }}
      </div>


      <div class="">
        {{ report.body|truncatechars:240 }}
      </div>
    </div>
  </a>
{% endfor %}

{% endif %}